#!/usr/bin/env bash

bake_supertask build "Various tasks for building the project"

bake_subtask build frontend "build the frontend"
function build-frontend () {
  echo "Building the frontend"
}

# Kinda redundent to include a bake_task declaration
# but this is to show that it does not interfere with aliases
bake_task run.my.program "Run the program"
function run.my.program () {
  echo "lets run the program! $*"
}

# Alias the "run.my.program" function to "run"
bake_task_alias run run.my.program "Run the program [alias]"
