#!/bin/bash
set -Eeuo pipefail

# @help.run-tests|In the ./test directory, runs `bake all` to run the unit test suite.
bake_task run-tests "Run tests"
run-tests () {
    (
        cd test
        bash ../bake all
    )
}

# @help.lint|Runs shellcheck (https://github.com/koalaman/shellcheck)
# @help.lint|against the bake itself, as well as the Bakefiles and test
# @help.lint|scripts in the repository.
bake_task lint "Lint the bake source files"
lint () {
    shellcheck \
        bake \
        Bakefile \
        ./test/Bakefile \
        ./test/lib/mylib.sh \
        ./test/impl/dir/bake/SubBakeFile \
        ./test/impl/file/Bakefile \
        ./test/lib/mylib.sh \
        ./test/sub/dir/a/SubBakeFileA \
        ./test/sub/dir/a/b/SubBakeFileB \
        ./test/sub/dir/a/b/c/SubBakeFileC \
        ./packages/vim/vim-go.sh \
        ./packages/vim/pathogen.sh \
        ./packages/bake/internal/test.sh \
        ./build/Bakefile \
        ./bake-completion.sh
}
